on:
   push:
    branches:
      - main


# permissions:
#   contents: read
#   pull-requests: read

# concurrency:
#     group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'



jobs:
  if_merged:
    # if: ${{ github.event.pull_request.merged }}    
    runs-on: ubuntu-22.04
    steps:
    - run: |
        echo The PR was merged
