on: 
   pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  pull-requests: read

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'


jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: main
    steps:
    - run: |
        echo The pull request was merged to main branch.
