on:
 pull_request_review:
    types: [submitted]
    branches:
      - main
  
# permissions:
#   contents: read
#   pull-requests: read

# concurrency:
#     group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'



jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
